# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, Awaitable

from azure.core import AsyncPipelineClient
from azure.core.rest import AsyncHttpResponse, HttpRequest

from .._serialization import Deserializer, Serializer
from ._configuration import WidgetManagerClientConfiguration
from .operations import (
    ListAsACoreResourceListOperations,
    ListAsAFoundationOperationOperations,
    ListAsAFoundationResourceListOperations,
)


class WidgetManagerClient:  # pylint: disable=client-accepts-api-version-keyword
    """WidgetManagerClient.

    :ivar list_as_afoundation_operation: ListAsAFoundationOperationOperations operations
    :vartype list_as_afoundation_operation:
     contoso.widgetmanager.aio.operations.ListAsAFoundationOperationOperations
    :ivar list_as_afoundation_resource_list: ListAsAFoundationResourceListOperations operations
    :vartype list_as_afoundation_resource_list:
     contoso.widgetmanager.aio.operations.ListAsAFoundationResourceListOperations
    :ivar list_as_acore_resource_list: ListAsACoreResourceListOperations operations
    :vartype list_as_acore_resource_list:
     contoso.widgetmanager.aio.operations.ListAsACoreResourceListOperations
    :param api_version: The API version to use for this operation. Required.
    :type api_version: str
    :keyword endpoint: Service host. Required.
    :paramtype endpoint: str
    """

    def __init__(  # pylint: disable=missing-client-constructor-parameter-credential
        self, api_version: str, *, endpoint: str, **kwargs: Any
    ) -> None:
        self._config = WidgetManagerClientConfiguration(api_version=api_version, **kwargs)
        self._client = AsyncPipelineClient(base_url=endpoint, config=self._config, **kwargs)

        self._serialize = Serializer()
        self._deserialize = Deserializer()
        self._serialize.client_side_validation = False
        self.list_as_afoundation_operation = ListAsAFoundationOperationOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.list_as_afoundation_resource_list = ListAsAFoundationResourceListOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.list_as_acore_resource_list = ListAsACoreResourceListOperations(
            self._client, self._config, self._serialize, self._deserialize
        )

    def send_request(self, request: HttpRequest, **kwargs: Any) -> Awaitable[AsyncHttpResponse]:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = await client.send_request(request)
        <AsyncHttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.AsyncHttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, **kwargs)

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> "WidgetManagerClient":
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details: Any) -> None:
        await self._client.__aexit__(*exc_details)
